### ISSUE TITLE
coupling with imagetransformer expects realpath to have the image's file extension

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FileManager#18]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
Depending on your version/configuration of php; uploaded files are stores in a Temp directory with a `.tmp` file extension; instead of the original file extension.

This causes the imagetransformer to break; failing the document upload. (f.e. `AppData\Local\Temp\php5E39.tmp`

### Steps to Reproduce
1. have an environment where the `realpath` doesn't match the file extension (e.x. Laragon on Windows)
2. try to upload an image using a documentable

### Expected behavior

image to upload, get optimized & added to the DB

### Actual behavior

image to upload to a temp directory, followed by a NotSupportedException as the file extension is `.tmp`
![image](https://user-images.githubusercontent.com/932193/48058995-46a12c80-e1b8-11e8-95de-f8c0402b413e.png)

![image](https://user-images.githubusercontent.com/932193/48059019-5751a280-e1b8-11e8-95ee-c226164c51d4.png)

**Comment by aocneanu** [comment]
Post an issue on intervention/image's repo, from your stacktrace it's pretty obvious that it's not related to Enso

**Comment by jlsjonas** [comment]
The issue is in the way that intervention/image is expecting the query. see [this SO](https://stackoverflow.com/questions/50061985/intervention-image-exception-notsupportedexception-encoding-format-tmp-is-not)

as a small digest:
the save api expects a valid image file extension; for the upload purpose, the stream() method should be used so that the actual format can be passed ([docs](http://image.intervention.io/api/stream)) 

or alternatively [their upload example](http://image.intervention.io/use/uploads)

**Comment by aocneanu** [comment]
I guess we can close this?

**Comment by jlsjonas** [comment]
I don't think so. However, the fix will likely be on https://github.com/laravel-enso/ImageTransformer/blob/master/src/app/Classes/ImageTransformer.php#L37, https://github.com/laravel-enso/ImageTransformer/blob/master/src/app/Classes/ImageTransformer.php#L52 & https://github.com/laravel-enso/ImageTransformer/blob/master/src/app/Classes/ImageTransformer.php#L67

so perhaps moved to the imageTransformer repo instead?

(for uploads you'd ideally want to use `Image::make(Input::file('photo'))->resize(300, 200)->save('foo.jpg');` instead; or alternatively using the stream syntax to minimize required changes `$categoryImage = Image::make($image)->resize(1600,479)->stream();`)

**Comment by aocneanu** [comment]
>so perhaps moved to the imageTransformer repo instead?

Clearly, but open it as a PR

**Comment by jlsjonas** [comment]
>Clearly

The issue affects only uploads; so it's not that _clearly_ imho.
A proper fix would actually need changes in both repo's most likely (to properly pass along the `Input::file('photo')`-like object)
