### ISSUE TITLE
Can't download files containing non-ascii characters

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/FileManager#22]
This is  a **bug**.

### Prerequisites
* [ ] Are you running the latest version? (3.x upgrade planned this week, but 99% sure it won't affect this bug
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Uploading a file containing a non-ascii character (ex.: `ü`) causes an error while trying to download the file (viewing works fine)
![image](https://user-images.githubusercontent.com/932193/54524163-86033500-4971-11e9-9dbc-1e02decc07f0.png)

### Steps to Reproduce
1. Upload a file containing a non-ascii character (ex. `test_ü.jpeg`)
2. Attempt downloading the file

### Expected behavior

File to be downloaded

### Actual behavior

bad _filename fallback_ passed causing an InvalidArgumentException

https://stackoverflow.com/a/23448597/620141 might help in fixing the bug.

**Comment by aocneanu** [comment]
it seems to be a Symfony HttpFoundation limit.

![image](https://user-images.githubusercontent.com/16073274/54682979-20ea4380-4b19-11e9-9fa7-61aa3341bab0.png)

Probably we could sanitize the file name before uploading, or on download. Are you looking for a solution like this?

**Comment by jlsjonas** [comment]
As it's a Symfony limit sanitizing is probably our best option. If you have a better idea to preserve full _localisation_ support I'm all ears though

**Comment by aocneanu** [comment]
I'm afraid I don't have a better idea.

**Comment by jlsjonas** [comment]
👌 Will you make the change or do I look into a PR for it?
